/** Banderas por equipo — local en web para evitar interop ESM/CJS. */
export const TEAM_FLAGS: Record<string, string> = {
  México: '🇲🇽',
  'Corea del Sur': '🇰🇷',
  Sudáfrica: '🇿🇦',
  Chequia: '🇨🇿',
  Canadá: '🇨🇦',
  'Bosnia y Herzegovina': '🇧🇦',
  Catar: '🇶🇦',
  Suiza: '🇨🇭',
  Brasil: '🇧🇷',
  Marruecos: '🇲🇦',
  Haití: '🇭🇹',
  Escocia: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Estados Unidos': '🇺🇸',
  Paraguay: '🇵🇾',
  Australia: '🇦🇺',
  Türkiye: '🇹🇷',
  Alemania: '🇩🇪',
  Curazao: '🇨🇼',
  'Costa de Marfil': '🇨🇮',
  Ecuador: '🇪🇨',
  'Países Bajos': '🇳🇱',
  Japón: '🇯🇵',
  Suecia: '🇸🇪',
  Túnez: '🇹🇳',
  Bélgica: '🇧🇪',
  Egipto: '🇪🇬',
  'IR Irán': '🇮🇷',
  'Nueva Zelanda': '🇳🇿',
  España: '🇪🇸',
  Uruguay: '🇺🇾',
  'Arabia Saudita': '🇸🇦',
  'Cabo Verde': '🇨🇻',
  Francia: '🇫🇷',
  Senegal: '🇸🇳',
  Noruega: '🇳🇴',
  Irak: '🇮🇶',
  Argentina: '🇦🇷',
  Argelia: '🇩🇿',
  Austria: '🇦🇹',
  Jordania: '🇯🇴',
  Portugal: '🇵🇹',
  Colombia: '🇨🇴',
  Uzbekistán: '🇺🇿',
  'Congo DR': '🇨🇩',
  Inglaterra: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Croacia: '🇭🇷',
  Ghana: '🇬🇭',
  Panamá: '🇵🇦',
};

export function getTeamFlag(team: string): string {
  return TEAM_FLAGS[team] ?? '🏳️';
}
